"""Compatibility regression for the shared full-search receipt codec rules.

Pins the byte-exact wire format of FullSearchReceipt, FullEncryptedSearchReceipt
and FullEncryptedJsonSearchReceipt — and of the signed envelopes embedding
their bytes — with fixed samples generated by the pre-refactor codecs, then
re-exercises the public boundary rules the refactor centralized: the common
head (magic, version, hash_name, size, root), the searched range, the listed
entries, the shared proof and the hit indices now flow through _CodecReader
and shared segment helpers, and these tests prove the observable contract
(TypeError/ValueError split, canonical bytes, decode/verify separation) is
unchanged.
"""

import base64
import json
import unittest
from dataclasses import FrozenInstanceError, astuple

from auditchain import (
    AuditLog,
    Entry,
    FullEncryptedJsonSearchReceipt,
    FullEncryptedSearchReceipt,
    FullSearchReceipt,
    decode_full_encrypted_json_search_receipt,
    decode_full_encrypted_search_receipt,
    decode_full_search_receipt,
    decode_signed_full_encrypted_search_receipt,
    decode_signed_full_search_receipt,
    encode_full_encrypted_json_search_receipt,
    encode_full_encrypted_search_receipt,
    encode_full_search_receipt,
    encode_signed_full_encrypted_search_receipt,
    encode_signed_full_search_receipt,
    verify_full_encrypted_json_search_receipt,
    verify_full_encrypted_search_receipt,
    verify_full_search_receipt,
    verify_signed_full_encrypted_search_receipt,
    verify_signed_full_search_receipt,
)

KEY = bytes(range(32))
OTHER_KEY = bytes(range(1, 33))
SIGN_SEED = bytes(range(1, 33))

SEARCH_MAGIC = b"auditchain/full-search/v1\0"
ENCRYPTED_MAGIC = b"auditchain/full-encrypted-search/v1\0"
JSON_MAGIC = b"auditchain/full-encrypted-json-search/v1\0"

SIGN_PUBLIC_B64 = "ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ="

GOLDEN_B64 = {
    "enc_empty_range": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAFAAAAAAAAACBHrlBchrBFngU+RzJN1O3GjLr+g89wfXQnKzqO9SPtagAAAAAAAAABYQAAAAAAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    "enc_empty_snapshot": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAAAAAAAAAAACAvBvO5nb4shiCc326uzXwAqzJJhzwdMR39POnb0b41twAAAAAAAAABYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    "enc_pruned": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAGAAAAAAAAACBtxkRwg0UCaMfy+k/FOIh6Xx+6kbCT1uuYfvTgqqr2OAAAAAAAAAABYgAAAAAAAAACAAAAAAAAAAYAAAAAAAAABAAAAAAAAAACAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABAgICAgICAgICAgIC+q5txuIDigT1ZzLeFd+gSYAAAAAAAAAAILb7isPFoWUlg4+lzfnKb+7XHi2BIhT7khNuRtknZxLbAAAAAAAAACAI4KRrq2jT9cD1k0XiB6DiV4ukByIDKu9tutP0n920ZQAAAAAAAAADAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABAwMDAwMDAwMDAwMDjVidpqXQf8jHy0PTrbJp7w4AAAAAAAAAIAjgpGuraNP1wPWTReIHoOJXi6QHIgMq72260/Sf3bRlAAAAAAAAACAl4bQKjNvjfelCOODBzbosPYmkHH31XwKZ+oquPeSq+AAAAAAAAAAEAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABBAQEBAQEBAQEBAQEBaFjl+CmwGrtNcEsUmNS9BAAAAAAAAAAICXhtAqM2+N96UI44MHNuiw9iaQcffVfApn6iq495Kr4AAAAAAAAACDfYmckHPs/hay3vjz0ogtrJgZQh2cO37G3ZMgERr9asgAAAAAAAAAFAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABBQUFBQUFBQUFBQUFLvuSa1kt32eTXGfO70b/gi4AAAAAAAAAIN9iZyQc+z+FrLe+PPSiC2smBlCHZw7fsbdkyARGv1qyAAAAAAAAACBVpoYN/K0x4Xg7iEzQrJQ76J8Y98N2rZwLlmcU9I+R/QAAAAAAAAABAAAAAAAAACB9NzBwuhK0e/sygJrej15Hu8qQS787fmQPs8rfecS/0wAAAAAAAAABAAAAAAAAAAU=",
    "enc_sha512": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTUxMgAAAAAAAAAFAAAAAAAAAEA2ZRJleb1gQA24bDBoCHGjOPh8MzmlDT2g3x8LrT5Kt9GlN51CeKuJu1qRNdfi9RskRYe4GAdRQDC26no1z5frAAAAAAAAAAFhAAAAAAAAAAEAAAAAAAAABAAAAAAAAAADAAAAAAAAAAEAAAAAAAAAPGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFF9kgLMppCGVQ07NEpSJrfIQAAAAAAAABA3F8+WFAahBSfxQnJZmE3rK+3JsGxwCtBiBPoDCZibDIyL5ZrXPr7MHCO7I5Yshj6e7ypMSh34yHn8xAkYnSnwQAAAAAAAABAVOQ5e4SPBHbw8qptegmjGQCmlvBr1+GOHcpjgIpq+WnenFU5VgZtunJsjCx1yAj63G6QjsuM9Iwl8b9zYrbTJgAAAAAAAAACAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyBg/p5pwKF4k3OXNkI6f+gBwAAAAAAAAAQFTkOXuEjwR28PKqbXoJoxkAppbwa9fhjh3KY4CKavlp3pxVOVYGbbpybIwsdcgI+txukI7LjPSMJfG/c2K20yYAAAAAAAAAQHjD4jJSYEkDxbD84rIDOx+ZHs0zlU/ZqtHZgd7fwNQUalZoj01e7cDgRIBqIeLNeY/NkWcyJJZuK++lPo08y2UAAAAAAAAAAwAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATMzMzMzMzMzMzMzMybSauwIwlyBs/PnOZoGXB9oAAAAAAAAAEB4w+IyUmBJA8Ww/OKyAzsfmR7NM5VP2arR2YHe38DUFGpWaI9NXu3A4ESAaiHizXmPzZFnMiSWbivvpT6NPMtlAAAAAAAAAEDEwmwUudBh2rIv8i+QPDw3MsBydOobWS4x+zr1TTSOaBivnKQMKOb7viip/Dyp1tOIfChCgvgm2BzYwyATQv4oAAAAAAAAAAIAAAAAAAAAQCFiD4xvSPFLk1RKXa9+R/TRJMxE0Y0QJL6TceuFy/6++koxHbyGUpUGqXlgJ4vap4yjNHCtmqjHmyGF9Ilz5PcAAAAAAAAAQCL/m+DynS11aMir54Gjak0GpL6rHoNY3bbyEvAXLutVl1SqGNmoJ8yWvdelW6JvgzxXsdK+KJtqXIYnOA5kw70AAAAAAAAAAQAAAAAAAAAC",
    "enc_subrange": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAFAAAAAAAAACBHrlBchrBFngU+RzJN1O3GjLr+g89wfXQnKzqO9SPtagAAAAAAAAABYQAAAAAAAAABAAAAAAAAAAQAAAAAAAAAAwAAAAAAAAABAAAAAAAAAAFiAAAAAAAAACB3REKZxIIfYUFXc+cEM42BeyIcB0yZ+8m4fFwi2BIA0wAAAAAAAAAgjVDJClffs8Mgc82zwYeTWX1wdqzieKZXWOKXLPaRm/4AAAAAAAAAAgAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAAQICAgICAgICAgICAvqWZ8WwA5fE9fpXEqDcO3ChAAAAAAAAACCNUMkKV9+zwyBzzbPBh5NZfXB2rOJ4pldY4pcs9pGb/gAAAAAAAAAgWTb6gqBM2frUtLa2f5vNGbHVrGAcXVUHYNr10yHpeD8AAAAAAAAAAwAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAAQMDAwMDAwMDAwMDA43LBRDiSLg/E/yn/y+yrZUKAAAAAAAAACBZNvqCoEzZ+tS0trZ/m80ZsdWsYBxdVQdg2vXTIel4PwAAAAAAAAAgPmII20BtrNmGx5TBUIFI95mu7vsYrjjzYYsqnG20xa8AAAAAAAAAAgAAAAAAAAAgtrSAmdWj4Wu4SvWKYOHyk5hnV1Z8flU3C25ksgy0WUoAAAAAAAAAIN34gjZ+9+BRezyB9aK46jEVaIH1uZHXYCXCgMHJZLSAAAAAAAAAAAEAAAAAAAAAAg==",
    "enc_whole": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAFAAAAAAAAACBHrlBchrBFngU+RzJN1O3GjLr+g89wfXQnKzqO9SPtagAAAAAAAAABYQAAAAAAAAAAAAAAAAAAAAUAAAAAAAAABQAAAAAAAAAAAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABAAAAAAAAAAAAAAAAb80o/dOrTi4rMFEcatKp4aEAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACB3REKZxIIfYUFXc+cEM42BeyIcB0yZ+8m4fFwi2BIA0wAAAAAAAAABAAAAAAAAAAFiAAAAAAAAACB3REKZxIIfYUFXc+cEM42BeyIcB0yZ+8m4fFwi2BIA0wAAAAAAAAAgjVDJClffs8Mgc82zwYeTWX1wdqzieKZXWOKXLPaRm/4AAAAAAAAAAgAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAAQICAgICAgICAgICAvqWZ8WwA5fE9fpXEqDcO3ChAAAAAAAAACCNUMkKV9+zwyBzzbPBh5NZfXB2rOJ4pldY4pcs9pGb/gAAAAAAAAAgWTb6gqBM2frUtLa2f5vNGbHVrGAcXVUHYNr10yHpeD8AAAAAAAAAAwAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAAQMDAwMDAwMDAwMDA43LBRDiSLg/E/yn/y+yrZUKAAAAAAAAACBZNvqCoEzZ+tS0trZ/m80ZsdWsYBxdVQdg2vXTIel4PwAAAAAAAAAgPmII20BtrNmGx5TBUIFI95mu7vsYrjjzYYsqnG20xa8AAAAAAAAABAAAAAAAAAA8YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAAQQEBAQEBAQEBAQEBAVxCfSUffDrF4KDvugt5y13AAAAAAAAACA+YgjbQG2s2YbHlMFQgUj3ma7u+xiuOPNhiyqcbbTFrwAAAAAAAAAgatZ0PkBthBCFG/K9EMGzx4xFYgOGHnJickMWxhWEd+4AAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAE",
    "full_empty_range": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAUAAAAAAAAAIKlhhyhVTb4oJr7huRrzz6GYYh/UeF3DcMyC3mKn8HrfAAAAAAAAAAFhAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAA=",
    "full_empty_snapshot": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAAAAAAAAAAAIC8G87mdviyGIJzfbq7NfACrMkmHPB0xHf086dvRvjW3AAAAAAAAAAFhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
    "full_pruned": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAII9ZDCUbZtLBLS4MQerr1eqiORSi7aYk62DwWC3goRwtAAAAAAAAAAFiAAAAAAAAAAIAAAAAAAAABgAAAAAAAAAEAAAAAAAAAAIAAAAAAAAAAWEAAAAAAAAAIF4wD02MezNTlqHtYJrURBVStqYKp54X7gfqnKGKgDctAAAAAAAAACCFp7s7O5EYQDz7oy2fQHAD6RF6YcprgMieuwD8HsUGywAAAAAAAAADAAAAAAAAAAFjAAAAAAAAACCFp7s7O5EYQDz7oy2fQHAD6RF6YcprgMieuwD8HsUGywAAAAAAAAAgP4zpRtlrOFlBTzjRsCmP6wtk0LSaYJDA5scfm4sstYcAAAAAAAAABAAAAAAAAAABYQAAAAAAAAAgP4zpRtlrOFlBTzjRsCmP6wtk0LSaYJDA5scfm4sstYcAAAAAAAAAIEPxRluhKENOWSGai+Q0WuRbFSMWlBk4JQRd5PlDhmnXAAAAAAAAAAUAAAAAAAAAAWIAAAAAAAAAIEPxRluhKENOWSGai+Q0WuRbFSMWlBk4JQRd5PlDhmnXAAAAAAAAACBtnQU7eX+NVvQm7vrxf3nwDZ8sMWxH2GxoMWCRTdJ+fAAAAAAAAAABAAAAAAAAACA3ItWRlwgezk/U1AABpc38jMEq7t3LSUTo8Toa9HaM7Q==",
    "full_sha512": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhNTEyAAAAAAAAAAUAAAAAAAAAQGxM3Mx/g2n1VWtrSzl8mKSCoRVPIeItI3NYDBJyB9ZMSaVrYN6+PY9EJ7K1uHCagnvzOc+GC+lv4wzlE5elaCsAAAAAAAAAAWEAAAAAAAAAAQAAAAAAAAAEAAAAAAAAAAMAAAAAAAAAAQAAAAAAAAABYgAAAAAAAABAo2G0y8bWmDSotFzxOylKAVjL0fN2PSK+/UpEYDFh95GQ1fHzHcn5P+P2GhhERIiHyC8E9j64VFFr9ZKs/tKKBgAAAAAAAABAfviRaS0oAeQEb/HTPN1hMEwozwCPxWxOanmVhF64KaMcVYlXQoQbp96YtetbTr6F1ZqeSBOK29UOZFOMR5LVygAAAAAAAAACAAAAAAAAAAFhAAAAAAAAAEB++JFpLSgB5ARv8dM83WEwTCjPAI/FbE5qeZWEXrgpoxxViVdChBun3pi161tOvoXVmp5IE4rb1Q5kU4xHktXKAAAAAAAAAECHn7FlrlLtD1eGEyMnTNFocn89Mxtzw9YDYlp4i3MEob4C0OG0rks63boeom8BKDr+Ycw2q6OHBeDo1T9ZmWFvAAAAAAAAAAMAAAAAAAAAAWMAAAAAAAAAQIefsWWuUu0PV4YTIydM0Whyfz0zG3PD1gNiWniLcwShvgLQ4bSuSzrduh6ibwEoOv5hzDaro4cF4OjVP1mZYW8AAAAAAAAAQOTGzBEA5x5vc+UJAig8/I6MxcP76o3fedVWSNBg5i1hj0ojSe03WGluIo1w85gFMSR/IzfWy0Tc/KMYVhbcFR4AAAAAAAAAAgAAAAAAAABAvJhzsRFGRp0FAAh1PNtO21KGdQPgUy19pD9K5duyTjdTGQ9rLNRS/9rUnN9ebBUgF3p/MujtdGrY1i80C8PXyQAAAAAAAABAPp8gDQaBsKt/Yv5xPphKcOXBCbOJHkHwjV3uryJDcFhBkVIaVADuyzV8AZKBiVGOiiSNVZrzIqRWDJAQ42RZpQ==",
    "full_subrange": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAUAAAAAAAAAIKlhhyhVTb4oJr7huRrzz6GYYh/UeF3DcMyC3mKn8HrfAAAAAAAAAAFhAAAAAAAAAAEAAAAAAAAABAAAAAAAAAADAAAAAAAAAAEAAAAAAAAAAWIAAAAAAAAAIFqyESWCqa2EVRWw8iyeoURERCUBb0/0bDPm5HccQJ/aAAAAAAAAACBeMA9NjHszU5ah7WCa1EQVUramCqeeF+4H6pyhioA3LQAAAAAAAAACAAAAAAAAAAFhAAAAAAAAACBeMA9NjHszU5ah7WCa1EQVUramCqeeF+4H6pyhioA3LQAAAAAAAAAghae7OzuRGEA8+6Mtn0BwA+kRemHKa4DInrsA/B7FBssAAAAAAAAAAwAAAAAAAAABYwAAAAAAAAAghae7OzuRGEA8+6Mtn0BwA+kRemHKa4DInrsA/B7FBssAAAAAAAAAID+M6UbZazhZQU840bApj+sLZNC0mmCQwObHH5uLLLWHAAAAAAAAAAIAAAAAAAAAICJWSEpuJ/ErHzc+D7pg+GAiLyy2hwVo548qsJ711V1NAAAAAAAAACBb8puscQTJJj1UZBPwS4Ue3lhFU/EPChOUCf22LMbtVA==",
    "full_whole": "YXVkaXRjaGFpbi9mdWxsLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAUAAAAAAAAAIKlhhyhVTb4oJr7huRrzz6GYYh/UeF3DcMyC3mKn8HrfAAAAAAAAAAFhAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAWEAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBashElgqmthFUVsPIsnqFEREQlAW9P9Gwz5uR3HECf2gAAAAAAAAABAAAAAAAAAAFiAAAAAAAAACBashElgqmthFUVsPIsnqFEREQlAW9P9Gwz5uR3HECf2gAAAAAAAAAgXjAPTYx7M1OWoe1gmtREFVK2pgqnnhfuB+qcoYqANy0AAAAAAAAAAgAAAAAAAAABYQAAAAAAAAAgXjAPTYx7M1OWoe1gmtREFVK2pgqnnhfuB+qcoYqANy0AAAAAAAAAIIWnuzs7kRhAPPujLZ9AcAPpEXphymuAyJ67APwexQbLAAAAAAAAAAMAAAAAAAAAAWMAAAAAAAAAIIWnuzs7kRhAPPujLZ9AcAPpEXphymuAyJ67APwexQbLAAAAAAAAACA/jOlG2Ws4WUFPONGwKY/rC2TQtJpgkMDmxx+biyy1hwAAAAAAAAAEAAAAAAAAAAFhAAAAAAAAACA/jOlG2Ws4WUFPONGwKY/rC2TQtJpgkMDmxx+biyy1hwAAAAAAAAAgQ/FGW6EoQ05ZIZqL5DRa5FsVIxaUGTglBF3k+UOGadcAAAAAAAAAAA==",
    "json_empty_range": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGGa2c1kH2fLl2DPCORJ4lJs1nhHTiJNDgIKbVcbVfTk=",
    "json_empty_snapshot": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAAAAAAAAAAAIC8G87mdviyGIJzfbq7NfACrMkmHPB0xHf086dvRvjW3AAAAAAAAAAIvYQAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgFQZP0BSEUVAA3pDPS9F0L8DOAzv8Vi9N5X0grOuXZUg=",
    "json_escaped_pointer": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAUvYX4xYgAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEwMDAwMDAwMDAwMDCSI7Fr6Huqvj/JAFQKzKtrWEgUqjIt1AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAAAEAAAAAAAAARGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFcXUmgneopHK0rwxsDMfRjx/LNZtCRn3zZAAAAAAAAACAJnfiSBrFH7Td3KAbCZZFmV7ywunZkYXxhe+9LImnUWwAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAAgAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATIyMjIyMjIyMjIyMhwCPDsXLiLyV/igLIBg7qZrZNrKbBooWaAAAAAAAAAAIDlFFjgjWfxkXW8yZjgsFO9RuUDBvCxsvfSdZFCE/EfFAAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAADAAAAAAAAAAd7ImEiOjF9AAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAAgeA2J6EQfDfDvsstonsXx+5ehnc8YbayumGefaCT1IrcAAAAAAAAABAAAAAAAAAA/YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATMzMzMzMzMzMzMzMz5y4Y44UB7ZfPX4iYbYx45FwAfzAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAgoga9+coKJ2+5nelTQ8m/OmvxYAE2N8apODW+y1/Mz5MAAAAAAAAABQAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATQ0NDQ0NDQ0NDQ0NBLfhabcppNXtxdzEHJco1uzmsvS3CKZAAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAgCnVpsy1wcYGLJfVHwTwR3+kUvyCvRcdUaZAU1d3vefAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBG4F4Spk6L7U2UMb+gp/ZmW/gbVa2hdHQHKXkznLS5mg==",
    "json_false": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAAAAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATAwMDAwMDAwMDAwMJIjsWvoe6q+P8kAVArMq2tYSBSqMi3UAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCZ34kgaxR+03dygGwmWRZle8sLp2ZGF8YXvvSyJp1FsAAAAAAAAAAQAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATExMTExMTExMTExMVxdSaCd6ikcrSvDGwMx9GPH8s1m0JGffNkAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAACA5RRY4I1n8ZF1vMmY4LBTvUblAwbwsbL30nWRQhPxHxQAAAAAAAAACAAAAAAAAAERhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyHAI8OxcuIvJX+KAsgGDupmtk2spsGihZoAAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAAAMAAAAAAAAAB3siYSI6MX0AAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAEAAAAAAAAAD9hdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMzMzMzMzMzMzMzMzPnLhjjhQHtl89fiJhtjHjkXAB/MAAAAAAAAAIHgNiehEHw3w77LLaJ7F8fuXoZ3PGG2srphnn2gk9SK3AAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAFAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABNDQ0NDQ0NDQ0NDQ0Et+Fptymk1e3F3MQclyjW7Oay9LcIpkAAAAAAAAAIKIGvfnKCidvuZ3pU0PJvzpr8WABNjfGqTg1vstfzM+TAAAAAAAAACAKdWmzLXBxgYsl9UfBPBHf6RS/IK9Fx1RpkBTV3e958AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIB5an+L7byU1tvcjpK+Ko90b33O3a27/8DX+eVPZXlD+",
    "json_float": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAACAAAAAAAAAAMxLjAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAAAAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATAwMDAwMDAwMDAwMJIjsWvoe6q+P8kAVArMq2tYSBSqMi3UAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCZ34kgaxR+03dygGwmWRZle8sLp2ZGF8YXvvSyJp1FsAAAAAAAAAAQAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATExMTExMTExMTExMVxdSaCd6ikcrSvDGwMx9GPH8s1m0JGffNkAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAACA5RRY4I1n8ZF1vMmY4LBTvUblAwbwsbL30nWRQhPxHxQAAAAAAAAACAAAAAAAAAERhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyHAI8OxcuIvJX+KAsgGDupmtk2spsGihZoAAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAAAMAAAAAAAAAB3siYSI6MX0AAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAEAAAAAAAAAD9hdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMzMzMzMzMzMzMzMzPnLhjjhQHtl89fiJhtjHjkXAB/MAAAAAAAAAIHgNiehEHw3w77LLaJ7F8fuXoZ3PGG2srphnn2gk9SK3AAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAFAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABNDQ0NDQ0NDQ0NDQ0Et+Fptymk1e3F3MQclyjW7Oay9LcIpkAAAAAAAAAIKIGvfnKCidvuZ3pU0PJvzpr8WABNjfGqTg1vstfzM+TAAAAAAAAACAKdWmzLXBxgYsl9UfBPBHf6RS/IK9Fx1RpkBTV3e958AAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAACCNSFbJaU90MFrkci6t2iH5XW0KxlQyisjJ4lycbSwb1A==",
    "json_int": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEwMDAwMDAwMDAwMDCSI7Fr6Huqvj/JAFQKzKtrWEgUqjIt1AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAAAEAAAAAAAAARGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFcXUmgneopHK0rwxsDMfRjx/LNZtCRn3zZAAAAAAAAACAJnfiSBrFH7Td3KAbCZZFmV7ywunZkYXxhe+9LImnUWwAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAAgAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATIyMjIyMjIyMjIyMhwCPDsXLiLyV/igLIBg7qZrZNrKbBooWaAAAAAAAAAAIDlFFjgjWfxkXW8yZjgsFO9RuUDBvCxsvfSdZFCE/EfFAAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAADAAAAAAAAAAd7ImEiOjF9AAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAAgeA2J6EQfDfDvsstonsXx+5ehnc8YbayumGefaCT1IrcAAAAAAAAABAAAAAAAAAA/YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATMzMzMzMzMzMzMzMz5y4Y44UB7ZfPX4iYbYx45FwAfzAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAgoga9+coKJ2+5nelTQ8m/OmvxYAE2N8apODW+y1/Mz5MAAAAAAAAABQAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATQ0NDQ0NDQ0NDQ0NBLfhabcppNXtxdzEHJco1uzmsvS3CKZAAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAgCnVpsy1wcYGLJfVHwTwR3+kUvyCvRcdUaZAU1d3vefAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAgRC1qOrivI3nyVMeCba5Ehcr6lLddZ998uJP1uGmg7+o=",
    "json_null": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAAAAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATAwMDAwMDAwMDAwMJIjsWvoe6q+P8kAVArMq2tYSBSqMi3UAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCZ34kgaxR+03dygGwmWRZle8sLp2ZGF8YXvvSyJp1FsAAAAAAAAAAQAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATExMTExMTExMTExMVxdSaCd6ikcrSvDGwMx9GPH8s1m0JGffNkAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAACA5RRY4I1n8ZF1vMmY4LBTvUblAwbwsbL30nWRQhPxHxQAAAAAAAAACAAAAAAAAAERhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyHAI8OxcuIvJX+KAsgGDupmtk2spsGihZoAAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAAAMAAAAAAAAAB3siYSI6MX0AAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAEAAAAAAAAAD9hdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMzMzMzMzMzMzMzMzPnLhjjhQHtl89fiJhtjHjkXAB/MAAAAAAAAAIHgNiehEHw3w77LLaJ7F8fuXoZ3PGG2srphnn2gk9SK3AAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAFAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABNDQ0NDQ0NDQ0NDQ0Et+Fptymk1e3F3MQclyjW7Oay9LcIpkAAAAAAAAAIKIGvfnKCidvuZ3pU0PJvzpr8WABNjfGqTg1vstfzM+TAAAAAAAAACAKdWmzLXBxgYsl9UfBPBHf6RS/IK9Fx1RpkBTV3e958AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIGAQadGtok02UdlB7s5OHH9qpqUQsHmp10raVgj2Pbh5",
    "json_pruned": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAIMeyWHBezsTo33XcMglUyrCV6N41Ojj7Mfx7mWFPkNraAAAAAAAAAAIvYQAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAIAAAAAAAAABgAAAAAAAAAEAAAAAAAAAAIAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAECAgICAgICAgICAgLgCniZg+hM9RHDUyRDQbPtNHZEB4QgOAAAAAAAAAAgRFNgpVk5KZ6MU470qDklqQAZW5DobfhcdDS2u3usK9AAAAAAAAAAIJTd4WwscM6Nm/4m1dV3krdsIm8Ng86n775HiJzuChjfAAAAAAAAAAMAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEDAwMDAwMDAwMDAwOVaV30MaAvHxQnkBK5reQpgWLE4uX7egAAAAAAAAAglN3hbCxwzo2b/ibV1XeSt2wibw2DzqfvvkeInO4KGN8AAAAAAAAAIEyWRY5UmPsfghwVaUPVgbr3tnbNJwAem9LmFQCjSU5AAAAAAAAAAAQAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEEBAQEBAQEBAQEBAQfpa+qE2Tso4WiqcCerM2w+Tan1CVHdgAAAAAAAAAgTJZFjlSY+x+CHBVpQ9WBuve2ds0nAB6b0uYVAKNJTkAAAAAAAAAAILrVNk9zMpgPdC0RTZX0bw0nzaYjt0hVDmHiiLpkyfk1AAAAAAAAAAUAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEFBQUFBQUFBQUFBQU3FLlTmgznOs4uw4298XPwkO/RV5sHsgAAAAAAAAAgutU2T3MymA90LRFNlfRvDSfNpiO3SFUOYeKIumTJ+TUAAAAAAAAAIL4m6h8r1Km1H3/6ec2rS+7lVTpCR3hFww8czRWoAGt4AAAAAAAAAAEAAAAAAAAAIKRtfRCB8zwiSmMygNDwJr/LG9Jq8yAsNXwktBAkrGH+AAAAAAAAAAMAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAUAAAAAAAAAINUFRu2fLxZz4V9emEE4tBRVaASkGaUIi9zyXrrhEegL",
    "json_sha512": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhNTEyAAAAAAAAAAMAAAAAAAAAQFRG/wAxjGhBzlJe0DD7YL88Bvi3IwI0ZEMzdR6kWQIwGUpYrfYJwHRZU8wQXucr3KjHAaMqztJm/9xmcbm0t/UAAAAAAAAAAi9hAAAAAAAAAAEAAAAAAAAAATEAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAMAAAAAAAAAAAAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATAwMDAwMDAwMDAwMJIjsWvoe6q/jE+N8qiTvsRdw4EztxkRAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECaI7fEZ4iJ2YRB94Fn1L+DrpP5lC5x5N7XNzrNdlkr6jL2dBAyD1PyLi1yVlAHoyzH2Z2dNKHg8BK50SPWYd+TAAAAAAAAAAEAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFcXUmgnep6PNN6b5y+1cqknvWomBorQQAAAAAAAABAmiO3xGeIidmEQfeBZ9S/g66T+ZQuceTe1zc6zXZZK+oy9nQQMg9T8i4tclZQB6Msx9mdnTSh4PASudEj1mHfkwAAAAAAAABAUEzvrUN+2g1mfF7TIOEWeQarfNcytEy2whFSK7DT10iUsf18iD3/N40huopWdL4r0tiXPogSTRnsa0V2hwbm/AAAAAAAAAACAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyHAI8Oxc+bhpNedeXK7gfL98C0/JWlPEAAAAAAAAAQFBM761DftoNZnxe0yDhFnkGq3zXMrRMtsIRUiuw09dIlLH9fIg9/zeNIbqKVnS+K9LYlz6IEk0Z7GtFdocG5vwAAAAAAAAAQC1xT4Ankzmma8/50pfc8MmNueOFR0YNNVqeZ1H1rUJXQABhMTm5S/KlhfMHmAyVjlnH5zbhV+qspX6r+roBuOkAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAQAAAAAAAABAUbcwJhBnl0XUSFbQDur5VqwciA00PpZb8IgGG+O80HhEBIKVPphnCZ2VSFwu5w+LHYt+59OnZJJ9/mMYgiXNhA==",
    "json_string": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAAAAAAAAAAAAAExAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEwMDAwMDAwMDAwMDCSI7Fr6Huqvj/JAFQKzKtrWEgUqjIt1AAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAAAEAAAAAAAAARGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFcXUmgneopHK0rwxsDMfRjx/LNZtCRn3zZAAAAAAAAACAJnfiSBrFH7Td3KAbCZZFmV7ywunZkYXxhe+9LImnUWwAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAAgAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATIyMjIyMjIyMjIyMhwCPDsXLiLyV/igLIBg7qZrZNrKbBooWaAAAAAAAAAAIDlFFjgjWfxkXW8yZjgsFO9RuUDBvCxsvfSdZFCE/EfFAAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAADAAAAAAAAAAd7ImEiOjF9AAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAAgeA2J6EQfDfDvsstonsXx+5ehnc8YbayumGefaCT1IrcAAAAAAAAABAAAAAAAAAA/YXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATMzMzMzMzMzMzMzMz5y4Y44UB7ZfPX4iYbYx45FwAfzAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAgoga9+coKJ2+5nelTQ8m/OmvxYAE2N8apODW+y1/Mz5MAAAAAAAAABQAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATQ0NDQ0NDQ0NDQ0NBLfhabcppNXtxdzEHJco1uzmsvS3CKZAAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAgCnVpsy1wcYGLJfVHwTwR3+kUvyCvRcdUaZAU1d3vefAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAIPZDRA+7+h4xZOhASjtEpOTu5Ndmg3wVbEqsAPdOp1gu",
    "json_subrange": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAQAAAAAAAAAIORQ3/3S1QCSvvDfW5+fm+DvR5WpNon/YIlAQoyngazGAAAAAAAAAAIvYQAAAAAAAAABAAAAAAAAAAExAAAAAAAAAAEAAAAAAAAABAAAAAAAAAADAAAAAAAAAAEAAAAAAAAARGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAExMTExMTExMTExMTFcXUmgneopHK0rwxsDMfRjx/LNZtCRn3zZAAAAAAAAACAJnfiSBrFH7Td3KAbCZZFmV7ywunZkYXxhe+9LImnUWwAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAAgAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATIyMjIyMjIyMjIyMhwCPDsXLiLyV/igLIBg7qZrZNrKbBooWaAAAAAAAAAAIDlFFjgjWfxkXW8yZjgsFO9RuUDBvCxsvfSdZFCE/EfFAAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAADAAAAAAAAAAd7ImEiOjF9AAAAAAAAACC4Us4A7u7XOx+2MYDiiU4FJyC4oQMC2ZvebuwQYhECZwAAAAAAAAAgeA2J6EQfDfDvsstonsXx+5ehnc8YbayumGefaCT1IrcAAAAAAAAAAQAAAAAAAAAg/XB1NtWZyNKk++O/xlLXlj/3tFYHrU81i25ySrMwOnEAAAAAAAAAAQAAAAAAAAABAAAAAAAAACD3Vf/kJDsA3C1brw5aHZDDFLD7TXeOhVEbQA33ChkhEA==",
    "json_true": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAIvYQAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAYAAAAAAAAAAAAAAAAAAABCYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATAwMDAwMDAwMDAwMJIjsWvoe6q+P8kAVArMq2tYSBSqMi3UAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCZ34kgaxR+03dygGwmWRZle8sLp2ZGF8YXvvSyJp1FsAAAAAAAAAAQAAAAAAAABEYXVkaXRjaGFpbi9lbmNyeXB0ZWQtZW50cnkvdjEAATExMTExMTExMTExMVxdSaCd6ikcrSvDGwMx9GPH8s1m0JGffNkAAAAAAAAAIAmd+JIGsUftN3coBsJlkWZXvLC6dmRhfGF770siadRbAAAAAAAAACA5RRY4I1n8ZF1vMmY4LBTvUblAwbwsbL30nWRQhPxHxQAAAAAAAAACAAAAAAAAAERhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMjIyMjIyMjIyMjIyHAI8OxcuIvJX+KAsgGDupmtk2spsGihZoAAAAAAAAAAgOUUWOCNZ/GRdbzJmOCwU71G5QMG8LGy99J1kUIT8R8UAAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAAAMAAAAAAAAAB3siYSI6MX0AAAAAAAAAILhSzgDu7tc7H7YxgOKJTgUnILihAwLZm95u7BBiEQJnAAAAAAAAACB4DYnoRB8N8O+yy2iexfH7l6GdzxhtrK6YZ59oJPUitwAAAAAAAAAEAAAAAAAAAD9hdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMzMzMzMzMzMzMzMzPnLhjjhQHtl89fiJhtjHjkXAB/MAAAAAAAAAIHgNiehEHw3w77LLaJ7F8fuXoZ3PGG2srphnn2gk9SK3AAAAAAAAACCiBr35ygonb7md6VNDyb86a/FgATY3xqk4Nb7LX8zPkwAAAAAAAAAFAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABNDQ0NDQ0NDQ0NDQ0Et+Fptymk1e3F3MQclyjW7Oay9LcIpkAAAAAAAAAIKIGvfnKCidvuZ3pU0PJvzpr8WABNjfGqTg1vstfzM+TAAAAAAAAACAKdWmzLXBxgYsl9UfBPBHf6RS/IK9Fx1RpkBTV3e958AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAILVJMRc4+7eHfDDYqMvNobXoGkYwZpa6fRp/brkPZhwd",
    "json_whole_pointer": "YXVkaXRjaGFpbi9mdWxsLWVuY3J5cHRlZC1qc29uLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAYAAAAAAAAAINsfhJXbsxWCtJr6X5woFwW1hbn2brzi2wHto7ZbaeI+AAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABMQAAAAAAAAAAAAAAAAAAAAYAAAAAAAAABgAAAAAAAAAAAAAAAAAAAEJhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMDAwMDAwMDAwMDAwkiOxa+h7qr4/yQBUCsyra1hIFKoyLdQAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAJnfiSBrFH7Td3KAbCZZFmV7ywunZkYXxhe+9LImnUWwAAAAAAAAABAAAAAAAAAERhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABMTExMTExMTExMTExXF1JoJ3qKRytK8MbAzH0Y8fyzWbQkZ982QAAAAAAAAAgCZ34kgaxR+03dygGwmWRZle8sLp2ZGF8YXvvSyJp1FsAAAAAAAAAIDlFFjgjWfxkXW8yZjgsFO9RuUDBvCxsvfSdZFCE/EfFAAAAAAAAAAIAAAAAAAAARGF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEyMjIyMjIyMjIyMjIcAjw7Fy4i8lf4oCyAYO6ma2TaymwaKFmgAAAAAAAAACA5RRY4I1n8ZF1vMmY4LBTvUblAwbwsbL30nWRQhPxHxQAAAAAAAAAguFLOAO7u1zsftjGA4olOBScguKEDAtmb3m7sEGIRAmcAAAAAAAAAAwAAAAAAAAAHeyJhIjoxfQAAAAAAAAAguFLOAO7u1zsftjGA4olOBScguKEDAtmb3m7sEGIRAmcAAAAAAAAAIHgNiehEHw3w77LLaJ7F8fuXoZ3PGG2srphnn2gk9SK3AAAAAAAAAAQAAAAAAAAAP2F1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAEzMzMzMzMzMzMzMzM+cuGOOFAe2Xz1+ImG2MeORcAH8wAAAAAAAAAgeA2J6EQfDfDvsstonsXx+5ehnc8YbayumGefaCT1IrcAAAAAAAAAIKIGvfnKCidvuZ3pU0PJvzpr8WABNjfGqTg1vstfzM+TAAAAAAAAAAUAAAAAAAAAQmF1ZGl0Y2hhaW4vZW5jcnlwdGVkLWVudHJ5L3YxAAE0NDQ0NDQ0NDQ0NDQS34Wm3KaTV7cXcxByXKNbs5rL0twimQAAAAAAAAAgoga9+coKJ2+5nelTQ8m/OmvxYAE2N8apODW+y1/Mz5MAAAAAAAAAIAp1abMtcHGBiyX1R8E8Ed/pFL8gr0XHVGmQFNXd73nwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgljes/Ykl/n6iUOyglnKx63lu6VxiiiAUaIrH/vLZ89k=",
    "signed_enc_envelope": "YXVkaXRjaGFpbi9zaWduZWQtZnVsbC1lbmNyeXB0ZWQtc2VhcmNoL3YxAAAAAAAAAAABAAAAAAAAAoxhdWRpdGNoYWluL2Z1bGwtZW5jcnlwdGVkLXNlYXJjaC92MQAAAAAAAAAAAQAAAAAAAAAGc2hhMjU2AAAAAAAAAAUAAAAAAAAAIEeuUFyGsEWeBT5HMk3U7caMuv6Dz3B9dCcrOo71I+1qAAAAAAAAAAFhAAAAAAAAAAEAAAAAAAAABAAAAAAAAAADAAAAAAAAAAEAAAAAAAAAAWIAAAAAAAAAIHdEQpnEgh9hQVdz5wQzjYF7IhwHTJn7ybh8XCLYEgDTAAAAAAAAACCNUMkKV9+zwyBzzbPBh5NZfXB2rOJ4pldY4pcs9pGb/gAAAAAAAAACAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABAgICAgICAgICAgIC+pZnxbADl8T1+lcSoNw7cKEAAAAAAAAAII1QyQpX37PDIHPNs8GHk1l9cHas4nimV1jilyz2kZv+AAAAAAAAACBZNvqCoEzZ+tS0trZ/m80ZsdWsYBxdVQdg2vXTIel4PwAAAAAAAAADAAAAAAAAADxhdWRpdGNoYWluL2VuY3J5cHRlZC1lbnRyeS92MQABAwMDAwMDAwMDAwMDjcsFEOJIuD8T/Kf/L7KtlQoAAAAAAAAAIFk2+oKgTNn61LS2tn+bzRmx1axgHF1VB2Da9dMh6Xg/AAAAAAAAACA+YgjbQG2s2YbHlMFQgUj3ma7u+xiuOPNhiyqcbbTFrwAAAAAAAAACAAAAAAAAACC2tICZ1aPha7hK9Ypg4fKTmGdXVnx+VTcLbmSyDLRZSgAAAAAAAAAg3fiCNn734FF7PIH1orjqMRVogfW5kddgJcKAwclktIAAAAAAAAAAAQAAAAAAAAACAAAAAAAAANBhdWRpdGNoYWluL3NpZ25lZC1yb290L3YxAAAAAAAAAAABAAAAAAAAAAZzaGEyNTYAAAAAAAAABQAAAAAAAAAgR65QXIawRZ4FPkcyTdTtxoy6/oPPcH10Jys6jvUj7WoAAAAAAAAAIGrWdD5AbYQQhRvyvRDBs8eMRWIDhh5yYnJDFsYVhHfuAAAAAAAAAEDjXY31yzwY2levcFjGLRRUWGFoNNcKQdTlr88KE+HUELXimsiH42q2A5Ubo89jhjhBQpnctky1F4Ch0cAl6RQD",
    "signed_full_envelope": "YXVkaXRjaGFpbi9zaWduZWQtZnVsbC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAB/GF1ZGl0Y2hhaW4vZnVsbC1zZWFyY2gvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAFAAAAAAAAACCpYYcoVU2+KCa+4bka88+hmGIf1Hhdw3DMgt5ip/B63wAAAAAAAAABYQAAAAAAAAABAAAAAAAAAAQAAAAAAAAAAwAAAAAAAAABAAAAAAAAAAFiAAAAAAAAACBashElgqmthFUVsPIsnqFEREQlAW9P9Gwz5uR3HECf2gAAAAAAAAAgXjAPTYx7M1OWoe1gmtREFVK2pgqnnhfuB+qcoYqANy0AAAAAAAAAAgAAAAAAAAABYQAAAAAAAAAgXjAPTYx7M1OWoe1gmtREFVK2pgqnnhfuB+qcoYqANy0AAAAAAAAAIIWnuzs7kRhAPPujLZ9AcAPpEXphymuAyJ67APwexQbLAAAAAAAAAAMAAAAAAAAAAWMAAAAAAAAAIIWnuzs7kRhAPPujLZ9AcAPpEXphymuAyJ67APwexQbLAAAAAAAAACA/jOlG2Ws4WUFPONGwKY/rC2TQtJpgkMDmxx+biyy1hwAAAAAAAAACAAAAAAAAACAiVkhKbifxKx83Pg+6YPhgIi8stocFaOePKrCe9dVdTQAAAAAAAAAgW/KbrHEEySY9VGQT8EuFHt5YRVPxDwoTlAn9tizG7VQAAAAAAAAA0GF1ZGl0Y2hhaW4vc2lnbmVkLXJvb3QvdjEAAAAAAAAAAAEAAAAAAAAABnNoYTI1NgAAAAAAAAAFAAAAAAAAACCpYYcoVU2+KCa+4bka88+hmGIf1Hhdw3DMgt5ip/B63wAAAAAAAAAgQ/FGW6EoQ05ZIZqL5DRa5FsVIxaUGTglBF3k+UOGadcAAAAAAAAAQJrCnsTicm34HlrNKkL2tikCr4V2dhW9b6an3/GKdIGDzbsOr9VaH8Sa7M9OCHwok7Rk10wxtuDDdI7myMTpnQ4=",
}

GOLDEN = {name: base64.b64decode(value) for name, value in GOLDEN_B64.items()}
SIGN_PUBLIC = base64.b64decode(SIGN_PUBLIC_B64)


def u64(value):
    return value.to_bytes(8, "big")


def blob(material):
    return u64(len(material)) + material


def j(value):
    return json.dumps(value, separators=(",", ":")).encode("utf-8")


def plain_log(records=("a", "b", "a", "c", "a"), hash_name="sha256"):
    log = AuditLog(hash_name=hash_name)
    for record in records:
        log.append(record)
    return log


def pruned_plain_log():
    log = plain_log(("a", "b", "a", "c", "a", "b"))
    log.prune(2, log.seal(2))
    return log


def encrypted_log(records=("a", "b", "a", "c", "a"), hash_name="sha256"):
    log = AuditLog(hash_name=hash_name)
    for nonce, value in enumerate(records):
        log.encrypt(value, KEY, nonce=bytes([nonce]) * 12)
    return log


def mixed_log():
    log = AuditLog()
    for nonce, (kind, value) in enumerate(
        (("enc", "a"), ("plain", "b"), ("enc", "a"), ("enc", "c"), ("enc", "a"))
    ):
        if kind == "enc":
            log.encrypt(value, KEY, nonce=bytes([nonce]) * 12)
        else:
            log.append(value)
    return log


def pruned_encrypted_log():
    log = encrypted_log(("a", "b", "a", "c", "a", "b"))
    log.prune(2, log.seal(2))
    return log


def sha512_encrypted_log():
    log = AuditLog(hash_name="sha512")
    for nonce, value in enumerate(("a", "b", "a", "c", "a")):
        log.encrypt(value, KEY, nonce=b"%d" % nonce * 12)
    return log


def json_log():
    log = AuditLog()
    log.encrypt(j({"a": 1}), KEY, nonce=b"0" * 12)
    log.encrypt(j({"a": 1.0}), KEY, nonce=b"1" * 12)
    log.encrypt(j({"a": "1"}), KEY, nonce=b"2" * 12)
    log.append(j({"a": 1}))
    log.encrypt(b"{bad", KEY, nonce=b"3" * 12)
    log.encrypt(j({"a": 1}), OTHER_KEY, nonce=b"4" * 12)
    return log


def pruned_json_log():
    log = AuditLog()
    for nonce, doc in enumerate(
        ({"a": 1}, {"a": "x"}, {"a": 1}, {"a": 2}, {"a": 1}, {"a": 1})
    ):
        log.encrypt(j(doc), KEY, nonce=bytes([nonce]) * 12)
    log.prune(2, log.seal(2))
    return log


def sha512_json_log():
    log = AuditLog(hash_name="sha512")
    log.encrypt(j({"a": 1}), KEY, nonce=b"0" * 12)
    log.encrypt(j({"a": 1}), KEY, nonce=b"1" * 12)
    log.encrypt(j({"a": 2}), KEY, nonce=b"2" * 12)
    return log


def full_search_samples():
    log = plain_log()
    log512 = plain_log(hash_name="sha512")
    return {
        "full_empty_snapshot": AuditLog().full_search_receipt("a"),
        "full_empty_range": log.full_search_receipt("a", 2, 2),
        "full_subrange": log.full_search_receipt("a", 1, 4),
        "full_whole": log.full_search_receipt("a"),
        "full_pruned": pruned_plain_log().full_search_receipt("b"),
        "full_sha512": log512.full_search_receipt("a", 1, 4),
    }


def encrypted_samples():
    log = mixed_log()
    return {
        "enc_empty_snapshot": AuditLog().full_encrypted_search_receipt("a", KEY),
        "enc_empty_range": log.full_encrypted_search_receipt("a", KEY, 2, 2),
        "enc_subrange": log.full_encrypted_search_receipt("a", KEY, 1, 4),
        "enc_whole": log.full_encrypted_search_receipt("a", KEY),
        "enc_pruned": pruned_encrypted_log().full_encrypted_search_receipt("b", KEY),
        "enc_sha512": sha512_encrypted_log().full_encrypted_search_receipt(
            "a", KEY, 1, 4
        ),
    }


def json_samples():
    log = json_log()
    return {
        "json_empty_snapshot": AuditLog().full_encrypted_json_search_receipt(
            "/a", 1, KEY
        ),
        "json_empty_range": log.full_encrypted_json_search_receipt(
            "/a", 1, KEY, 2, 2, size=6
        ),
        "json_int": log.full_encrypted_json_search_receipt("/a", 1, KEY),
        "json_float": log.full_encrypted_json_search_receipt("/a", 1.0, KEY),
        "json_string": log.full_encrypted_json_search_receipt("/a", "1", KEY),
        "json_true": log.full_encrypted_json_search_receipt("/a", True, KEY),
        "json_false": log.full_encrypted_json_search_receipt("/a", False, KEY),
        "json_null": log.full_encrypted_json_search_receipt("/a", None, KEY),
        "json_whole_pointer": log.full_encrypted_json_search_receipt("", 1, KEY),
        "json_escaped_pointer": log.full_encrypted_json_search_receipt(
            "/a~1b", 1, KEY
        ),
        "json_subrange": log.full_encrypted_json_search_receipt(
            "/a", 1, KEY, 1, 4, size=4
        ),
        "json_pruned": pruned_json_log().full_encrypted_json_search_receipt(
            "/a", 1, KEY
        ),
        "json_sha512": sha512_json_log().full_encrypted_json_search_receipt(
            "/a", 1, KEY
        ),
    }


class GoldenFullSearchReceiptTest(unittest.TestCase):
    """Pre-refactor bytes still decode, and re-encode byte-identically."""

    def check_golden(self, name, receipt, encode, decode, verify):
        data = GOLDEN[name]
        self.assertEqual(encode(receipt), data)
        decoded = decode(data)
        self.assertEqual(decoded, receipt)
        self.assertEqual(encode(decoded), data)
        self.assertTrue(verify(decoded))

    def test_full_search_samples(self):
        for name, receipt in full_search_samples().items():
            with self.subTest(name=name):
                self.check_golden(
                    name,
                    receipt,
                    encode_full_search_receipt,
                    decode_full_search_receipt,
                    verify_full_search_receipt,
                )

    def test_encrypted_samples(self):
        for name, receipt in encrypted_samples().items():
            with self.subTest(name=name):
                self.check_golden(
                    name,
                    receipt,
                    encode_full_encrypted_search_receipt,
                    decode_full_encrypted_search_receipt,
                    lambda r: verify_full_encrypted_search_receipt(r, KEY),
                )

    def test_json_samples(self):
        for name, receipt in json_samples().items():
            with self.subTest(name=name):
                self.check_golden(
                    name,
                    receipt,
                    encode_full_encrypted_json_search_receipt,
                    decode_full_encrypted_json_search_receipt,
                    lambda r: verify_full_encrypted_json_search_receipt(r, KEY),
                )

    def test_pruned_samples_use_absolute_indices(self):
        decoded = decode_full_search_receipt(GOLDEN["full_pruned"])
        self.assertEqual(decoded.start, 2)
        self.assertEqual(
            tuple(entry.index for entry in decoded.items), (2, 3, 4, 5)
        )
        decoded = decode_full_encrypted_search_receipt(GOLDEN["enc_pruned"])
        self.assertEqual(decoded.start, 2)
        self.assertEqual(
            tuple(entry.index for entry in decoded.items), (2, 3, 4, 5)
        )
        decoded = decode_full_encrypted_json_search_receipt(GOLDEN["json_pruned"])
        self.assertEqual(decoded.start, 2)
        self.assertEqual(
            tuple(entry.index for entry in decoded.items), (2, 3, 4, 5)
        )

    def test_digest_widths(self):
        for name, decode in (
            ("full_sha512", decode_full_search_receipt),
            ("enc_sha512", decode_full_encrypted_search_receipt),
            ("json_sha512", decode_full_encrypted_json_search_receipt),
        ):
            with self.subTest(name=name):
                decoded = decode(GOLDEN[name])
                self.assertEqual(decoded.hash_name, "sha512")
                self.assertEqual(len(decoded.root), 64)
                for node in decoded.proof:
                    self.assertEqual(len(node), 64)

    def test_signed_envelopes_still_verify(self):
        bundle = decode_signed_full_search_receipt(GOLDEN["signed_full_envelope"])
        self.assertTrue(verify_signed_full_search_receipt(bundle, SIGN_PUBLIC))
        self.assertEqual(
            encode_signed_full_search_receipt(bundle),
            GOLDEN["signed_full_envelope"],
        )
        # The signed bytes reference the very receipt encoding pinned above.
        self.assertEqual(
            encode_full_search_receipt(bundle.receipt), GOLDEN["full_subrange"]
        )
        bundle = decode_signed_full_encrypted_search_receipt(
            GOLDEN["signed_enc_envelope"]
        )
        self.assertTrue(
            verify_signed_full_encrypted_search_receipt(bundle, KEY, SIGN_PUBLIC)
        )
        self.assertEqual(
            encode_signed_full_encrypted_search_receipt(bundle),
            GOLDEN["signed_enc_envelope"],
        )
        self.assertEqual(
            encode_full_encrypted_search_receipt(bundle.receipt),
            GOLDEN["enc_subrange"],
        )


class SharedBoundaryTest(unittest.TestCase):
    """The boundary rules the refactor centralized behave exactly as before."""

    DECODERS = (
        decode_full_search_receipt,
        decode_full_encrypted_search_receipt,
        decode_full_encrypted_json_search_receipt,
    )
    ENCODERS = (
        encode_full_search_receipt,
        encode_full_encrypted_search_receipt,
        encode_full_encrypted_json_search_receipt,
    )
    MAGICS = (SEARCH_MAGIC, ENCRYPTED_MAGIC, JSON_MAGIC)
    SAMPLES = ("full_subrange", "enc_subrange", "json_int")

    def test_only_bytes_accepted(self):
        for decode, sample in zip(self.DECODERS, self.SAMPLES):
            data = GOLDEN[sample]
            for bad in (bytearray(data), memoryview(data), "text", None, 1):
                with self.subTest(decode=decode.__name__, bad=type(bad)):
                    with self.assertRaises(TypeError):
                        decode(bad)

    def test_encode_type_errors(self):
        for encode in self.ENCODERS:
            for bad in (None, "receipt", b"bytes", 1, (1, 2)):
                with self.subTest(encode=encode.__name__, bad=type(bad)):
                    with self.assertRaises(TypeError):
                        encode(bad)

    def test_bad_magic(self):
        for decode, magic, sample in zip(self.DECODERS, self.MAGICS, self.SAMPLES):
            data = GOLDEN[sample]
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(b"x" + data[1:])
                with self.assertRaises(ValueError):
                    decode(b"")
                with self.assertRaises(ValueError):
                    decode(magic[:-1])

    def test_bad_version(self):
        for decode, magic, sample in zip(self.DECODERS, self.MAGICS, self.SAMPLES):
            data = GOLDEN[sample]
            forged = magic + u64(2) + data[len(magic) + 8:]
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(forged)

    def test_truncation_at_every_offset(self):
        for decode, magic, sample in zip(self.DECODERS, self.MAGICS, self.SAMPLES):
            data = GOLDEN[sample]
            with self.subTest(decode=decode.__name__):
                for cut in range(len(magic), len(data)):
                    with self.assertRaises(ValueError):
                        decode(data[:cut])

    def test_trailing_bytes(self):
        for decode, sample in zip(self.DECODERS, self.SAMPLES):
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(GOLDEN[sample] + b"\x00")

    def test_oversized_blob_length(self):
        for decode, magic in zip(self.DECODERS, self.MAGICS):
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(magic + u64(1) + u64(1 << 63) + b"sha256")

    def test_invalid_utf8_hash_name(self):
        for decode, magic in zip(self.DECODERS, self.MAGICS):
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(magic + u64(1) + blob(b"\xff\xfe"))

    def test_unknown_hash_algorithm(self):
        for decode, magic in zip(self.DECODERS, self.MAGICS):
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(magic + u64(1) + blob(b"not-a-hash") + b"\x00" * 64)

    def test_digest_width_checked(self):
        # A 31-byte root under sha256 is rejected by every decoder.
        for decode, magic in zip(self.DECODERS, self.MAGICS):
            with self.subTest(decode=decode.__name__):
                with self.assertRaises(ValueError):
                    decode(
                        magic
                        + u64(1)
                        + blob(b"sha256")
                        + u64(0)
                        + blob(b"\x00" * 31)
                    )

    def test_proof_node_count_checked(self):
        log = plain_log()
        receipt = log.full_search_receipt("a", 1, 4)
        for bad_proof in ((), receipt.proof + (b"\x00" * 32,)):
            forged = FullSearchReceipt.__new__(FullSearchReceipt)
            for name, value in (
                ("version", 1),
                ("hash_name", "sha256"),
                ("size", 5),
                ("root", log.merkle_root()),
                ("query", b"a"),
                ("start", 1),
                ("stop", 4),
                ("items", receipt.items),
                ("proof", bad_proof),
            ):
                object.__setattr__(forged, name, value)
            with self.assertRaises(ValueError):
                decode_full_search_receipt(encode_full_search_receipt(forged))

    def test_hit_indices_checked(self):
        log = mixed_log()
        receipt = log.full_encrypted_search_receipt("a", KEY)
        for bad_hits in ((0, 0), (2, 1), (5,)):
            forged = FullEncryptedSearchReceipt.__new__(FullEncryptedSearchReceipt)
            for name, value in (
                ("version", 1),
                ("hash_name", "sha256"),
                ("size", receipt.size),
                ("root", receipt.root),
                ("query", b"a"),
                ("start", 0),
                ("stop", 5),
                ("items", receipt.items),
                ("proof", receipt.proof),
                ("hits", bad_hits),
            ):
                object.__setattr__(forged, name, value)
            with self.subTest(hits=bad_hits):
                with self.assertRaises(ValueError):
                    decode_full_encrypted_search_receipt(
                        encode_full_encrypted_search_receipt(forged)
                    )

    def test_json_pointer_and_value_checked(self):
        # Invalid UTF-8 in the pointer blob.
        with self.assertRaises(ValueError):
            decode_full_encrypted_json_search_receipt(
                JSON_MAGIC
                + u64(1)
                + blob(b"sha256")
                + u64(0)
                + blob(b"\x00" * 32)
                + blob(b"\xff\xfe")
            )
        # An unknown value type tag.
        with self.assertRaises(ValueError):
            decode_full_encrypted_json_search_receipt(
                JSON_MAGIC
                + u64(1)
                + blob(b"sha256")
                + u64(0)
                + blob(b"\x00" * 32)
                + blob(b"/a")
                + u64(99)
                + blob(b"1")
            )


class TamperBoundaryTest(unittest.TestCase):
    """Structural validity and authenticity stay separate after the refactor."""

    def test_tampered_full_search_receipt_roundtrips_and_fails_verification(self):
        log = plain_log()
        receipt = log.full_search_receipt("a")
        entry = receipt.items[0]
        forged_entry = Entry(entry.index, b"zz", entry.previous_hash, entry.entry_hash)
        tampered = FullSearchReceipt(
            1,
            "sha256",
            receipt.size,
            receipt.root,
            receipt.query,
            receipt.start,
            receipt.stop,
            (forged_entry,) + receipt.items[1:],
            receipt.proof,
        )
        data = encode_full_search_receipt(tampered)
        decoded = decode_full_search_receipt(data)
        self.assertEqual(decoded, tampered)
        self.assertEqual(encode_full_search_receipt(decoded), data)
        self.assertFalse(verify_full_search_receipt(decoded))

    def test_tampered_encrypted_receipt_roundtrips_and_fails_verification(self):
        log = mixed_log()
        receipt = log.full_encrypted_search_receipt("a", KEY)
        entry = receipt.items[0]
        forged_entry = Entry(
            entry.index, entry.payload + b"\x00", entry.previous_hash,
            entry.entry_hash,
        )
        tampered = FullEncryptedSearchReceipt(
            1,
            "sha256",
            receipt.size,
            receipt.root,
            receipt.query,
            receipt.start,
            receipt.stop,
            (forged_entry,) + receipt.items[1:],
            receipt.proof,
            receipt.hits,
        )
        data = encode_full_encrypted_search_receipt(tampered)
        decoded = decode_full_encrypted_search_receipt(data)
        self.assertEqual(decoded, tampered)
        self.assertEqual(encode_full_encrypted_search_receipt(decoded), data)
        self.assertFalse(verify_full_encrypted_search_receipt(decoded, KEY))

    def test_tampered_json_receipt_roundtrips_and_fails_verification(self):
        log = json_log()
        receipt = log.full_encrypted_json_search_receipt("/a", 1, KEY)
        confirmation = bytes([receipt.confirmation[0] ^ 1]) + receipt.confirmation[1:]
        tampered = FullEncryptedJsonSearchReceipt(
            1,
            "sha256",
            receipt.size,
            receipt.root,
            receipt.pointer,
            receipt.value,
            receipt.start,
            receipt.stop,
            receipt.items,
            receipt.proof,
            receipt.hits,
            confirmation,
        )
        data = encode_full_encrypted_json_search_receipt(tampered)
        decoded = decode_full_encrypted_json_search_receipt(data)
        self.assertEqual(decoded, tampered)
        self.assertEqual(encode_full_encrypted_json_search_receipt(decoded), data)
        self.assertFalse(verify_full_encrypted_json_search_receipt(decoded, KEY))

    def test_wrong_key_fails_verification_but_not_decoding(self):
        log = mixed_log()
        receipt = log.full_encrypted_search_receipt("a", KEY)
        decoded = decode_full_encrypted_search_receipt(
            encode_full_encrypted_search_receipt(receipt)
        )
        self.assertFalse(verify_full_encrypted_search_receipt(decoded, OTHER_KEY))
        log = json_log()
        receipt = log.full_encrypted_json_search_receipt("/a", 1, KEY)
        decoded = decode_full_encrypted_json_search_receipt(
            encode_full_encrypted_json_search_receipt(receipt)
        )
        self.assertFalse(
            verify_full_encrypted_json_search_receipt(decoded, OTHER_KEY)
        )


class ReadOnlyTest(unittest.TestCase):
    """Encoding and decoding mutate neither the receipt nor the log."""

    def test_encode_leaves_receipt_and_log_untouched(self):
        log = mixed_log()
        root_before = log.merkle_root()
        receipt = log.full_encrypted_search_receipt("a", KEY)
        fields_before = astuple(receipt)
        data = encode_full_encrypted_search_receipt(receipt)
        self.assertEqual(astuple(receipt), fields_before)
        self.assertEqual(log.merkle_root(), root_before)
        decoded = decode_full_encrypted_search_receipt(data)
        self.assertEqual(astuple(receipt), fields_before)
        self.assertEqual(log.merkle_root(), root_before)
        self.assertEqual(decoded, receipt)

    def test_decoded_receipt_is_frozen(self):
        decoded = decode_full_search_receipt(GOLDEN["full_subrange"])
        with self.assertRaises(FrozenInstanceError):
            decoded.query = b"other"


if __name__ == "__main__":
    unittest.main()
